<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use DoctrineExtensions\Query\Mysql;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * query for fixtures
     *
     * @return QueryBuilder
     */
    public function getAllCustomers()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Customer', 'c');

        return $qb;
    }

    /**
     * @return object[]
     */
    public function getByLastMonth()
    {
        $startDate  = new \Datetime(date('Y-m-d', strtotime('-1 month', time())));
        $endDate    = new \Datetime();

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
                ->from('AppBundle:Customer', 'c')
                ->where('c.registerDate BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime('@'.$startDate->getTimestamp()))
                ->setParameter('end', new \DateTime('@'.$endDate->getTimestamp()));

        return $qb->getQuery()->getResult();
    }

}
