<?php

namespace AppBundle\Repository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return object[]
     */
    public function getMostPopularProduct()
    {
       $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('SUM(o.quantity) as sales','p.name','p.price')
                ->from('AppBundle:OrderDetail', 'o')
                ->leftJoin('o.product', 'p')
                ->groupBy('o.product')
                ->addOrderBy('sales', 'DESC')
                ->setMaxResults(1);

        return $qb->getQuery()->getResult();
    }

}
